# pytest.ini
[pytest]
addopts = --strict-markers
markers =
    # Маркер с описанием:
    slow: Very slow tests
    # Маркер без описания.
    web
# Минимально требуемая версия pytest:
minversion = 9.0
# Список директорий для поиска тестов:
testpaths = .